# Generated by Django 4.2.1 on 2024-03-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountstorage', '0003_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('web', 'Web portal'), ('ssh', 'SSH Server'), ('database', 'Database')], max_length=255),
        ),
    ]
