# Generated by Django 4.2.1 on 2024-06-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountstorage', '0004_alter_account_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sshaccount',
            old_name='link',
            new_name='host',
        ),
    ]
