# Generated by Django 4.2.1 on 2024-06-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='encrypted_private_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
